dataset:
  ds_path: "D:\\ai intro\\dataset"
net:
  img: [128,128]
  n1: 16
  n2: 32
  n3: 64
train:
  bs: 32
  lr: 0.001
  n_epochs: 100
  opt: Adam
test:
  exp_path: "D:\\ai intro\\Pytorch\\Clasificare_py_torch\\Experiment_dataset_mare03022022_1355\\Weights\\my_model03022022_1522_e90.pt"